# Bước 1: Đọc và Tìm hiểu Dữ liệu (Data Understanding)

Notebook này thực hiện các bước tìm hiểu tổng quan về tập dữ liệu học lực học sinh `Student_Performance.csv` (25,000 dòng).

In [4]:
import os
import sys
import joblib
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error, accuracy_score, classification_report, confusion_matrix

print("Imported necessary libraries successfully!")

Imported necessary libraries successfully!

## 1. Đọc dữ liệu (`Student_Performance.csv`)

In [5]:
# Tìm đường dẫn tệp raw data bằng cách leo lên các thư mục cha
data_path = 'data/raw/Student_Performance.csv'
for _ in range(5):
    if os.path.exists(data_path):
        break
    data_path = os.path.join('..', data_path)

df_raw = pd.read_csv(data_path)

# Chuẩn hóa khoảng trắng tên cột nếu có
df_raw.columns = df_raw.columns.str.strip()

print(f"Raw dataset shape: {df_raw.shape[0]} rows, {df_raw.shape[1]} columns")
df_raw.head()

Raw dataset shape: 25000 rows, 16 columns

,student_id,age,gender,school_type,parent_education,study_hours,attendance_percentage,internet_access,travel_time,extra_activities,study_method,math_score,science_score,english_score,overall_score,final_grade
0,1,14,male,public,post graduate,3.1,84.3,yes,<15 min,yes,notes,42.7,55.4,57.0,53.1,e
1,2,18,female,public,graduate,3.7,87.8,yes,>60 min,no,textbook,57.6,68.8,64.8,61.3,d
2,3,17,female,private,post graduate,7.9,65.5,no,<15 min,no,notes,84.8,95.0,79.2,89.6,b
3,4,16,other,public,high school,1.1,58.1,no,15-30 min,no,notes,44.4,27.5,54.7,41.6,e
4,5,16,female,public,high school,1.3,61.0,yes,30-60 min,yes,group study,8.9,32.7,30.0,25.4,f

### 1.1. Khám phá tổng quan dữ liệu (Data Understanding / Overview)

In [6]:
# 1. Kiểm tra thông tin các cột và kiểu dữ liệu
print("--- THÔNG TIN CẤU TRÚC DỮ LIỆU ---")
df_raw.info()

# 2. Thống kê mô tả dữ liệu số
print("\n--- THỐNG KÊ MÔ TẢ ĐẶC TRƯNG SỐ ---")
display(df_raw.describe())

# 3. Kiểm tra các giá trị khuyết thiếu (Missing values)
print("\n--- KIỂM TRA GIÁ TRỊ KHUYẾT THIẾU (NULL/NAN) ---")
print(df_raw.isnull().sum())

--- THÔNG TIN CẤU TRÚC DỮ LIỆU ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 16 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   student_id             25000 non-null  int64
 1   age                    25000 non-null  int64
 2   gender                 25000 non-null  object
 3   school_type            25000 non-null  object
 4   parent_education       25000 non-null  object
 5   study_hours            25000 non-null  float64
 6   attendance_percentage  25000 non-null  float64
 7   internet_access        25000 non-null  object
 8   travel_time            25000 non-null  object
 9   extra_activities       25000 non-null  object
 10  study_method           25000 non-null  object
 11  math_score             25000 non-null  float64
 12  science_score          25000 non-null  float64
 13  english_score          25000 non-null  float64
 14  overall_score          25000 non-null  float64
 15  final_grade            25000 non-null  object
dtypes: float64(6), int64(2), object(8)
memory usage: 3.1+ MB

--- THỐNG KÊ MÔ TẢ ĐẶC TRƯNG SỐ ---

,student_id,age,study_hours,attendance_percentage,math_score,science_score,english_score,overall_score
count,25000.00000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000
mean,7493.04380,16.482760,4.253224,75.084084,63.785944,63.745320,63.681948,64.006172
std,4323.56215,1.703895,2.167541,14.373171,20.875262,20.970529,20.792693,18.932025
min,1.00000,14.000000,0.500000,50.000000,0.000000,0.000000,0.000000,14.500000
25%,3743.75000,15.000000,2.400000,62.800000,48.300000,48.200000,48.300000,49.000000
50%,7461.50000,16.000000,4.300000,75.100000,64.100000,64.100000,64.200000,64.200000
75%,11252.00000,18.000000,6.100000,87.500000,80.000000,80.000000,80.000000,79.000000
max,15000.00000,19.000000,8.000000,100.000000,100.000000,100.000000,100.000000,100.000000

--- KIỂM TRA GIÁ TRỊ KHUYẾT THIẾU (NULL/NAN) ---
student_id               0
age                      0
gender                   0
school_type              0
parent_education         0
study_hours              0
attendance_percentage    0
internet_access          0
travel_time              0
extra_activities         0
study_method             0
math_score               0
science_score            0
english_score            0
overall_score            0
final_grade              0
dtype: int64